### ISSUE TITLE
Specify which version of the service supports which technology

### ISSUE THREAD

**Issue by dibericky** [dibericky/matrix-compatibility#2]
The matrix compatiblity should specify the technology compatibility (e.g.: mongo) for each version of the service.
An example is shown here: https://www.mongodb.com/docs/ops-manager/current/reference/mongodb-compatibility/#mongodb-versions-compatible-with-mms

The version taken in consideration could be specified in the configuration, or maybe could be specified the semversion level ([major], or [major, minor] or [major, minor, patch]).
If the version is [major, minor] than will be taken up to N tags (descending order) considering only the major and minor.
If the version is [major] than will be taken up to N tags considering only the major.

**Comment by fredmaggiowski** [comment]
I've found this library that maybe handy for checking semver of tags: https://docs.rs/semver/latest/semver/
